const admin = require('firebase-admin');
const serviceAccount = require('./service-account-key.json'); // You'll need to download this from Firebase

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount)
});

const db = admin.firestore();

const ngos = [
  // ===============================================
  // 1. NAGPUR, MAHARASHTRA (20 ENTRIES)
  // ===============================================
  {
    "name": "Nari Shakti Sansthan",
    "services": ["Legal Aid", "Counseling", "Shelter", "Medical Help", "Rehabilitation"],
    "languages": ["Marathi", "Hindi", "English"],
    "verified": true,
    "contact": "+91-712-4010101",
    "region": "Nagpur",
    "state": "Maharashtra",
    "lat": 21.145800,
    "lng": 79.088200,
    "address": "45, Civil Lines Road, Near High Court, Nagpur - 440001"
  },
  {
    "name": "Mahila Adhar Kendra",
    "services": ["Counseling", "Shelter", "Medical Help"],
    "languages": ["Marathi", "Hindi"],
    "verified": true,
    "contact": "+91-712-2554321",
    "region": "Nagpur",
    "state": "Maharashtra",
    "lat": 21.162000,
    "lng": 79.065000,
    "address": "Plot 10, Ramdaspeth, Beside Axis Bank, Nagpur - 440010"
  },
  {
    "name": "Hope Foundation for Women",
    "services": ["Legal Aid", "Counseling", "Rehabilitation"],
    "languages": ["English", "Hindi"],
    "verified": false,
    "contact": "+91-712-6678900",
    "region": "Nagpur",
    "state": "Maharashtra",
    "lat": 21.139900,
    "lng": 79.102500,
    "address": "A/12, Sadar Bazaar, Near Railway Station, Nagpur - 440007"
  },
  {
    "name": "Vanita Suraksha Samiti",
    "services": ["Shelter", "Medical Help", "Rehabilitation"],
    "languages": ["Marathi"],
    "verified": true,
    "contact": "+91-712-3001122",
    "region": "Nagpur",
    "state": "Maharashtra",
    "lat": 21.150500,
    "lng": 79.080100,
    "address": "Wardha Road Bypass, Opposite Reliance Mall, Nagpur - 440025"
  },
  {
    "name": "Astitva Women's Collective",
    "services": ["Legal Aid", "Counseling"],
    "languages": ["English", "Marathi"],
    "verified": true,
    "contact": "+91-712-4567890",
    "region": "Nagpur",
    "state": "Maharashtra",
    "lat": 21.173000,
    "lng": 79.055000,
    "address": "78, Dharampeth Extension, IT Park Road, Nagpur - 440015"
  },
  {
    "name": "Stree Mukti Abhiyan, Nagpur",
    "services": ["Counseling", "Legal Aid"],
    "languages": ["Hindi", "Marathi"],
    "verified": true,
    "contact": "+91-712-2345678",
    "region": "Nagpur",
    "state": "Maharashtra",
    "lat": 21.128700,
    "lng": 79.115400,
    "address": "Ganeshpeth, Behind Bus Stand, Nagpur - 440018"
  },
  {
    "name": "Vidarbha Women's Rights",
    "services": ["Legal Aid", "Rehabilitation"],
    "languages": ["Marathi", "English"],
    "verified": true,
    "contact": "+91-712-8880001",
    "region": "Nagpur",
    "state": "Maharashtra",
    "lat": 21.160300,
    "lng": 79.091700,
    "address": "Laxmi Nagar, Near NIT Garden, Nagpur - 440022"
  },
  {
    "name": "Jyoti Women's Cell",
    "services": ["Shelter", "Counseling"],
    "languages": ["Hindi", "Marathi"],
    "verified": true,
    "contact": "+91-712-7100000",
    "region": "Nagpur",
    "state": "Maharashtra",
    "lat": 21.140200,
    "lng": 79.071500,
    "address": "Hanuman Nagar, Opp. Water Tank, Nagpur - 440009"
  },
  {
    "name": "Samarthya Mahila Sangh",
    "services": ["Legal Aid", "Medical Help"],
    "languages": ["Marathi"],
    "verified": false,
    "contact": "+91-712-9090909",
    "region": "Nagpur",
    "state": "Maharashtra",
    "lat": 21.178500,
    "lng": 79.083200,
    "address": "Mominpura, Central Avenue Road, Nagpur - 440003"
  },
  {
    "name": "Care India - Nagpur Branch",
    "services": ["Rehabilitation", "Counseling"],
    "languages": ["English", "Hindi"],
    "verified": true,
    "contact": "+91-712-4050607",
    "region": "Nagpur",
    "state": "Maharashtra",
    "lat": 21.132000,
    "lng": 79.095000,
    "address": "Hingna MIDC Area, Road No. 5, Nagpur - 440028"
  },
  {
    "name": "Umeed Women Support",
    "services": ["Legal Aid", "Shelter"],
    "languages": ["Hindi", "Marathi"],
    "verified": true,
    "contact": "+91-712-2113355",
    "region": "Nagpur",
    "state": "Maharashtra",
    "lat": 21.185000,
    "lng": 79.060000,
    "address": "Gokulpeth Main Road, Near Coffee House, Nagpur - 440016"
  },
  {
    "name": "Savita Stree Kalyan",
    "services": ["Counseling", "Medical Help"],
    "languages": ["Marathi"],
    "verified": true,
    "contact": "+91-712-2200220",
    "region": "Nagpur",
    "state": "Maharashtra",
    "lat": 21.148000,
    "lng": 79.110500,
    "address": "Bajaj Nagar, Plot No. 15, Nagpur - 440024"
  },
  {
    "name": "Shakti Vahini Nagpur",
    "services": ["Legal Aid", "Shelter", "Rehabilitation"],
    "languages": ["Hindi", "English"],
    "verified": true,
    "contact": "+91-712-4090807",
    "region": "Nagpur",
    "state": "Maharashtra",
    "lat": 21.168000,
    "lng": 79.070000,
    "address": "Manewada Ring Road, Opp. SBI, Nagpur - 440034"
  },
  {
    "name": "Centre for Women's Justice, Nagpur",
    "services": ["Legal Aid"],
    "languages": ["English", "Marathi"],
    "verified": true,
    "contact": "+91-712-2349876",
    "region": "Nagpur",
    "state": "Maharashtra",
    "lat": 21.135000,
    "lng": 79.088000,
    "address": "Near Central Jail Chowk, Central Avenue, Nagpur - 440004"
  },
  {
    "name": "Nirbhaya Mahila Trust",
    "services": ["Shelter", "Counseling"],
    "languages": ["Hindi", "Marathi"],
    "verified": true,
    "contact": "+91-712-5000055",
    "region": "Nagpur",
    "state": "Maharashtra",
    "lat": 21.155500,
    "lng": 79.075500,
    "address": "Itwari Market Road, 3rd Floor, Nagpur - 440002"
  },
  {
    "name": "Jeevan Asha Helpdesk",
    "services": ["Medical Help", "Counseling"],
    "languages": ["Marathi", "Hindi"],
    "verified": false,
    "contact": "+91-712-3211234",
    "region": "Nagpur",
    "state": "Maharashtra",
    "lat": 21.170500,
    "lng": 79.095000,
    "address": "Ajni Chowk, Near Railway Bridge, Nagpur - 440012"
  },
  {
    "name": "Navjeevan Women's Shelter",
    "services": ["Shelter", "Rehabilitation"],
    "languages": ["Hindi", "Marathi"],
    "verified": true,
    "contact": "+91-712-9988776",
    "region": "Nagpur",
    "state": "Maharashtra",
    "lat": 21.129000,
    "lng": 79.068000,
    "address": "Sonegaon Airport Road, Opposite Fuel Station, Nagpur - 440026"
  },
  {
    "name": "Women's Empowerment Hub",
    "services": ["Legal Aid", "Rehabilitation"],
    "languages": ["English", "Hindi"],
    "verified": true,
    "contact": "+91-712-4455667",
    "region": "Nagpur",
    "state": "Maharashtra",
    "lat": 21.144000,
    "lng": 79.072000,
    "address": "Civil Lines, Back of Collector Office, Nagpur - 440001"
  },
  {
    "name": "Aadarsh Mahila Manch",
    "services": ["Counseling", "Medical Help"],
    "languages": ["Marathi"],
    "verified": true,
    "contact": "+91-712-6543210",
    "region": "Nagpur",
    "state": "Maharashtra",
    "lat": 21.180000,
    "lng": 79.100000,
    "address": "Khamla Square, Near Post Office, Nagpur - 440025"
  },
  {
    "name": "Disha Women's Rights",
    "services": ["Legal Aid", "Shelter"],
    "languages": ["Hindi", "English"],
    "verified": true,
    "contact": "+91-712-2901290",
    "region": "Nagpur",
    "state": "Maharashtra",
    "lat": 21.157000,
    "lng": 79.085000,
    "address": "Shankar Nagar, Plot 55, Nagpur - 440010"
  },
  // ===============================================
  // 2. MAHARASHTRA, Excluding NAGPUR (50 ENTRIES)
  // ===============================================
  // 2.1. Mumbai (25 Entries)
  {
    "name": "Majlis Legal Centre",
    "services": ["Legal Aid", "Counseling", "Rehabilitation"],
    "languages": ["Marathi", "Hindi", "English"],
    "verified": true,
    "contact": "+91-22-26401314",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.030000,
    "lng": 72.850000,
    "address": "A-2, Apna Ghar, S.V. Road, Bandra West, Mumbai - 400050"
  },
  {
    "name": "Snehalaya Mumbai Shelter",
    "services": ["Shelter", "Medical Help", "Rehabilitation"],
    "languages": ["Marathi", "Hindi"],
    "verified": true,
    "contact": "+91-22-30005000",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.117000,
    "lng": 72.880000,
    "address": "Near Powai Lake, Chandivali Road, Andheri East, Mumbai - 400072"
  },
  {
    "name": "Forum Against Oppression of Women",
    "services": ["Counseling", "Legal Aid"],
    "languages": ["English", "Marathi"],
    "verified": true,
    "contact": "+91-22-24321010",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 18.960000,
    "lng": 72.820000,
    "address": "Tardeo Road, Opposite Haji Ali Dargah, Mumbai - 400034"
  },
  {
    "name": "Akshara Centre",
    "services": ["Rehabilitation", "Counseling"],
    "languages": ["Hindi", "English"],
    "verified": true,
    "contact": "+91-22-66667777",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.070000,
    "lng": 72.870000,
    "address": "Navi Mumbai, Sector 17, Vashi, Mumbai - 400703"
  },
  {
    "name": "Women's India Trust (WIT)",
    "services": ["Rehabilitation", "Shelter"],
    "languages": ["Marathi", "Hindi", "Gujarati"],
    "verified": true,
    "contact": "+91-22-25559090",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.098000,
    "lng": 72.845000,
    "address": "Juhu Tara Road, Near Iskcon Temple, Santacruz West, Mumbai - 400049"
  },
  {
    "name": "Pragati Legal Services",
    "services": ["Legal Aid"],
    "languages": ["English", "Marathi"],
    "verified": true,
    "contact": "+91-22-28001000",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.170000,
    "lng": 72.830000,
    "address": "Borivali West, Near S.V.P Garden, Mumbai - 400092"
  },
  {
    "name": "Sahyog Counselling Unit",
    "services": ["Counseling", "Medical Help"],
    "languages": ["Hindi", "Marathi"],
    "verified": false,
    "contact": "+91-22-25112233",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.078000,
    "lng": 72.905000,
    "address": "Chembur East, Near Diamond Garden, Mumbai - 400071"
  },
  {
    "name": "Aasha Griha Shelter Home",
    "services": ["Shelter", "Rehabilitation"],
    "languages": ["Marathi", "Hindi"],
    "verified": true,
    "contact": "+91-22-35003500",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.230000,
    "lng": 72.855000,
    "address": "Mira Road East, Shanti Nagar, Mumbai - 401107"
  },
  {
    "name": "Women Help Line 181, Mumbai",
    "services": ["Counseling", "Legal Aid", "Shelter"],
    "languages": ["Marathi", "Hindi", "English"],
    "verified": true,
    "contact": "181",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.010000,
    "lng": 72.840000,
    "address": "State Govt. Initiative, Mantralaya, Mumbai - 400032"
  },
  {
    "name": "Stree Mukti Sanghatana, Mumbai",
    "services": ["Counseling", "Rehabilitation"],
    "languages": ["Marathi"],
    "verified": true,
    "contact": "+91-22-27778899",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.055000,
    "lng": 73.020000,
    "address": "Kharghar Sector 2, Central Park Road, Navi Mumbai - 410210"
  },
  {
    "name": "Apna Adhikar Abhiyan",
    "services": ["Legal Aid", "Medical Help"],
    "languages": ["Hindi", "Marathi"],
    "verified": true,
    "contact": "+91-22-24345678",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.125000,
    "lng": 72.865000,
    "address": "Goregaon West, Link Road, Mumbai - 400062"
  },
  {
    "name": "Awaaz Foundation - Women's Wing",
    "services": ["Counseling", "Legal Aid"],
    "languages": ["English", "Hindi"],
    "verified": true,
    "contact": "+91-22-29012901",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.100000,
    "lng": 72.825000,
    "address": "Lokhandwala Complex, Andheri West, Mumbai - 400053"
  },
  {
    "name": "Disha Shelter Services",
    "services": ["Shelter", "Rehabilitation"],
    "languages": ["Marathi", "Hindi"],
    "verified": true,
    "contact": "+91-22-28445566",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.200000,
    "lng": 72.860000,
    "address": "Dahisar East, Near Check Naka, Mumbai - 400068"
  },
  {
    "name": "Kiran Women's Care Unit",
    "services": ["Medical Help", "Counseling"],
    "languages": ["Hindi", "English"],
    "verified": false,
    "contact": "+91-22-67891234",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 18.990000,
    "lng": 72.830000,
    "address": "Colaba Causeway, Near Regal Cinema, Mumbai - 400005"
  },
  {
    "name": "Mumbai Legal Aid Forum",
    "services": ["Legal Aid"],
    "languages": ["Marathi", "English"],
    "verified": true,
    "contact": "+91-22-23456789",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.035000,
    "lng": 72.860000,
    "address": "Parel, Near KEM Hospital, Mumbai - 400012"
  },
  {
    "name": "Sanjeevani Mahila Kendra",
    "services": ["Counseling", "Shelter"],
    "languages": ["Hindi", "Marathi"],
    "verified": true,
    "contact": "+91-22-40404040",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.140000,
    "lng": 72.930000,
    "address": "Mulund West, R.K. Road, Mumbai - 400080"
  },
  {
    "name": "Jyoti Women Development Center",
    "services": ["Rehabilitation", "Counseling"],
    "languages": ["English", "Hindi"],
    "verified": true,
    "contact": "+91-22-27889900",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.075000,
    "lng": 73.000000,
    "address": "Sector 10, Nerul, Navi Mumbai - 400706"
  },
  {
    "name": "Sakhi Women's Network",
    "services": ["Legal Aid", "Shelter", "Medical Help"],
    "languages": ["Marathi", "Hindi", "English"],
    "verified": true,
    "contact": "+91-22-26490000",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.100000,
    "lng": 72.840000,
    "address": "Khar West, 14th Road, Mumbai - 400052"
  },
  {
    "name": "Prerna Mahila Sanstha",
    "services": ["Counseling"],
    "languages": ["Marathi"],
    "verified": false,
    "contact": "+91-22-41122334",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 18.970000,
    "lng": 72.835000,
    "address": "Fort Area, Near Fountain, Mumbai - 400001"
  },
  {
    "name": "New Horizons for Women",
    "services": ["Rehabilitation"],
    "languages": ["English", "Hindi"],
    "verified": true,
    "contact": "+91-22-25805805",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.155000,
    "lng": 72.950000,
    "address": "Thane West, Gokhale Road, Mumbai - 400602"
  },
  {
    "name": "Navjeevan Women's Aid",
    "services": ["Shelter", "Medical Help"],
    "languages": ["Hindi", "Marathi"],
    "verified": true,
    "contact": "+91-22-27515151",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.040000,
    "lng": 73.025000,
    "address": "CBD Belapur, Sector 11, Navi Mumbai - 400614"
  },
  {
    "name": "Adhikar Legal Aid Society",
    "services": ["Legal Aid", "Counseling"],
    "languages": ["Marathi", "English"],
    "verified": true,
    "contact": "+91-22-67006700",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.160000,
    "lng": 72.845000,
    "address": "Malad West, Infinity Mall Road, Mumbai - 400064"
  },
  {
    "name": "Vishweshwari Women's Trust",
    "services": ["Rehabilitation", "Counseling"],
    "languages": ["Hindi", "Marathi"],
    "verified": true,
    "contact": "+91-22-42104210",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.080000,
    "lng": 72.915000,
    "address": "Ghatkopar East, Pant Nagar, Mumbai - 400075"
  },
  {
    "name": "Swaraksha Mahila Kendra",
    "services": ["Shelter"],
    "languages": ["Marathi"],
    "verified": false,
    "contact": "+91-22-23334444",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.180000,
    "lng": 72.900000,
    "address": "Kalyan East, Near Station, Mumbai - 421301"
  },
  {
    "name": "Udaan Women's Initiative",
    "services": ["Legal Aid", "Counseling", "Rehabilitation"],
    "languages": ["English", "Hindi"],
    "verified": true,
    "contact": "+91-22-25002500",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.130000,
    "lng": 72.840000,
    "address": "Versova, Yari Road, Andheri West, Mumbai - 400061"
  },
  // 2.2. Pune (15 Entries)
  {
    "name": "Streevani Pune",
    "services": ["Counseling", "Rehabilitation"],
    "languages": ["Marathi", "English"],
    "verified": true,
    "contact": "+91-20-26123456",
    "region": "Pune",
    "state": "Maharashtra",
    "lat": 18.520400,
    "lng": 73.856700,
    "address": "S.B. Road, Near Pune University, Pune - 411016"
  },
  {
    "name": "Swadhar IDWC Pune",
    "services": ["Shelter", "Legal Aid", "Counseling"],
    "languages": ["Marathi", "Hindi"],
    "verified": true,
    "contact": "+91-20-24447000",
    "region": "Pune",
    "state": "Maharashtra",
    "lat": 18.510000,
    "lng": 73.840000,
    "address": "Deccan Gymkhana, Fergusson College Road, Pune - 411004"
  },
  {
    "name": "Nirbhaya Mahila Manch, Pune",
    "services": ["Legal Aid", "Medical Help"],
    "languages": ["Hindi", "Marathi"],
    "verified": true,
    "contact": "+91-20-65432100",
    "region": "Pune",
    "state": "Maharashtra",
    "lat": 18.560000,
    "lng": 73.910000,
    "address": "Kharadi Bypass Road, Eon Free Zone, Pune - 411014"
  },
  {
    "name": "Sakhi Women's Support Centre, Pune",
    "services": ["Counseling", "Shelter"],
    "languages": ["Marathi", "English"],
    "verified": true,
    "contact": "+91-20-27278000",
    "region": "Pune",
    "state": "Maharashtra",
    "lat": 18.610000,
    "lng": 73.740000,
    "address": "Hinjewadi Phase 2, IT Park, Pune - 411057"
  },
  {
    "name": "Vatsalya Pune Trust",
    "services": ["Rehabilitation", "Shelter"],
    "languages": ["Hindi", "Marathi"],
    "verified": true,
    "contact": "+91-20-30009999",
    "region": "Pune",
    "state": "Maharashtra",
    "lat": 18.460000,
    "lng": 73.890000,
    "address": "Kondhwa Budruk, Near NIBM Road, Pune - 411048"
  },
  {
    "name": "Janani Legal Services, Pune",
    "services": ["Legal Aid"],
    "languages": ["English", "Marathi"],
    "verified": true,
    "contact": "+91-20-25678901",
    "region": "Pune",
    "state": "Maharashtra",
    "lat": 18.530000,
    "lng": 73.800000,
    "address": "Pimple Saudagar, Near Rainbow Bridge, Pune - 411027"
  },
  {
    "name": "Disha Women's Rights Cell",
    "services": ["Counseling", "Legal Aid"],
    "languages": ["Marathi", "Hindi"],
    "verified": true,
    "contact": "+91-20-66005500",
    "region": "Pune",
    "state": "Maharashtra",
    "lat": 18.570000,
    "lng": 73.880000,
    "address": "Viman Nagar, Near Phoenix Marketcity, Pune - 411014"
  },
  {
    "name": "Pune Mahila Kalyan Samiti",
    "services": ["Medical Help", "Rehabilitation"],
    "languages": ["Hindi", "Marathi"],
    "verified": true,
    "contact": "+91-20-24478899",
    "region": "Pune",
    "state": "Maharashtra",
    "lat": 18.500000,
    "lng": 73.840000,
    "address": "Tilak Road, Near SP College, Pune - 411030"
  },
  {
    "name": "Adarsh Mahila Trust, Pune",
    "services": ["Shelter"],
    "languages": ["Marathi"],
    "verified": false,
    "contact": "+91-20-32103210",
    "region": "Pune",
    "state": "Maharashtra",
    "lat": 18.580000,
    "lng": 73.930000,
    "address": "Hadapsar Industrial Area, Pune - 411013"
  },
  {
    "name": "Jyoti Women's Shelter, Pune",
    "services": ["Counseling", "Rehabilitation"],
    "languages": ["English", "Hindi"],
    "verified": true,
    "contact": "+91-20-27776655",
    "region": "Pune",
    "state": "Maharashtra",
    "lat": 18.590000,
    "lng": 73.780000,
    "address": "Bavdhan, Mumbai-Pune Bypass, Pune - 411021"
  },
  {
    "name": "Shakti Legal Aid Center, Pune",
    "services": ["Legal Aid"],
    "languages": ["Marathi", "Hindi"],
    "verified": true,
    "contact": "+91-20-66334455",
    "region": "Pune",
    "state": "Maharashtra",
    "lat": 18.480000,
    "lng": 73.870000,
    "address": "Camp Area, East Street, Pune - 411001"
  },
  {
    "name": "Pune Women's Shelter Home",
    "services": ["Shelter", "Medical Help"],
    "languages": ["Hindi", "Marathi"],
    "verified": true,
    "contact": "+91-20-40004000",
    "region": "Pune",
    "state": "Maharashtra",
    "lat": 18.540000,
    "lng": 73.900000,
    "address": "Yerwada, Near Golf Course, Pune - 411006"
  },
  {
    "name": "Kiran Women Empowerment",
    "services": ["Rehabilitation", "Counseling"],
    "languages": ["English", "Marathi"],
    "verified": true,
    "contact": "+91-20-25890000",
    "region": "Pune",
    "state": "Maharashtra",
    "lat": 18.505000,
    "lng": 73.850000,
    "address": "Shivajinagar, J.M. Road, Pune - 411005"
  },
  {
    "name": "Astitva Mahila Seva",
    "services": ["Legal Aid", "Shelter"],
    "languages": ["Marathi"],
    "verified": false,
    "contact": "+91-20-42223333",
    "region": "Pune",
    "state": "Maharashtra",
    "lat": 18.600000,
    "lng": 73.700000,
    "address": "Talegaon Dabhade, Old Mumbai Pune Highway, Pune - 410507"
  },
  {
    "name": "Parivartan Women Trust",
    "services": ["Counseling", "Medical Help"],
    "languages": ["Hindi", "English"],
    "verified": true,
    "contact": "+91-20-67896789",
    "region": "Pune",
    "state": "Maharashtra",
    "lat": 18.550000,
    "lng": 73.830000,
    "address": "Baner Road, Near Balewadi High Street, Pune - 411045"
  },
  // 2.3. Rest of Maharashtra (10 Entries)
  {
    "name": "Aurangabad Mahila Adhikar",
    "services": ["Legal Aid", "Counseling"],
    "languages": ["Marathi", "Hindi"],
    "verified": true,
    "contact": "+91-240-2345678",
    "region": "Aurangabad",
    "state": "Maharashtra",
    "lat": 19.876200,
    "lng": 75.343300,
    "address": "Jalna Road, Near CIDCO Bus Stand, Aurangabad - 431005"
  },
  {
    "name": "Nashik Stree Kalyan Trust",
    "services": ["Shelter", "Rehabilitation"],
    "languages": ["Marathi"],
    "verified": true,
    "contact": "+91-253-2579000",
    "region": "Nashik",
    "state": "Maharashtra",
    "lat": 19.997500,
    "lng": 73.789800,
    "address": "Gangapur Road, Near Sula Vineyards, Nashik - 422013"
  },
  {
    "name": "Thane Mahila Suraksha",
    "services": ["Legal Aid", "Counseling", "Medical Help"],
    "languages": ["Hindi", "Marathi", "English"],
    "verified": true,
    "contact": "+91-22-25470000",
    "region": "Thane",
    "state": "Maharashtra",
    "lat": 19.218300,
    "lng": 72.978100,
    "address": "Eastern Express Highway, Near Viviana Mall, Thane - 400601"
  },
  {
    "name": "Kolhapur Women's Justice Forum",
    "services": ["Legal Aid"],
    "languages": ["Marathi"],
    "verified": false,
    "contact": "+91-231-2651010",
    "region": "Kolhapur",
    "state": "Maharashtra",
    "lat": 16.705000,
    "lng": 74.243300,
    "address": "Rajaram Road, Near KMC Chowk, Kolhapur - 416008"
  },
  {
    "name": "Amravati Sakhi Kendra",
    "services": ["Counseling", "Shelter"],
    "languages": ["Marathi", "Hindi"],
    "verified": true,
    "contact": "+91-721-2558899",
    "region": "Amravati",
    "state": "Maharashtra",
    "lat": 20.937400,
    "lng": 77.779700,
    "address": "Badnera Road, Near Railway Overbridge, Amravati - 444605"
  },
  {
    "name": "Latur Women's Aid Society",
    "services": ["Rehabilitation", "Medical Help"],
    "languages": ["Marathi"],
    "verified": true,
    "contact": "+91-2382-245678",
    "region": "Latur",
    "state": "Maharashtra",
    "lat": 18.406900,
    "lng": 76.560200,
    "address": "Ausa Road, Near Shivaji Chowk, Latur - 413512"
  },
  {
    "name": "Jalgaon Mahila Adhar",
    "services": ["Legal Aid", "Shelter"],
    "languages": ["Hindi", "Marathi"],
    "verified": true,
    "contact": "+91-257-2234567",
    "region": "Jalgaon",
    "state": "Maharashtra",
    "lat": 21.007500,
    "lng": 75.562600,
    "address": "M.J. College Road, Near Bus Stop, Jalgaon - 425001"
  },
  {
    "name": "Solapur Women's Rights Trust",
    "services": ["Counseling", "Rehabilitation"],
    "languages": ["Marathi"],
    "verified": true,
    "contact": "+91-217-2720101",
    "region": "Solapur",
    "state": "Maharashtra",
    "lat": 17.659900,
    "lng": 75.906400,
    "address": "Hotgi Road, Near Solapur University, Solapur - 413003"
  },
  {
    "name": "Sangli Stree Mukti Abhiyan",
    "services": ["Legal Aid", "Medical Help"],
    "languages": ["Marathi", "Hindi"],
    "verified": false,
    "contact": "+91-233-2234455",
    "region": "Sangli",
    "state": "Maharashtra",
    "lat": 16.852400,
    "lng": 74.578600,
    "address": "Vishrambagh Circle, Opp. Post Office, Sangli - 416416"
  },
  {
    "name": "Parbhani Mahila Suraksha",
    "services": ["Shelter", "Counseling"],
    "languages": ["Marathi"],
    "verified": true,
    "contact": "+91-2452-250505",
    "region": "Parbhani",
    "state": "Maharashtra",
    "lat": 19.261800,
    "lng": 76.764500,
    "address": "Bus Stand Road, Near Government Hospital, Parbhani - 431401"
  },
  // 2.4. Additional Mumbai/Pune Fillers (15 Entries)
  {
    "name": "Punarvashan Welfare Trust",
    "services": ["Rehabilitation"],
    "languages": ["Hindi", "Marathi", "English"],
    "verified": true,
    "contact": "+91-22-29998888",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.120000,
    "lng": 72.840000,
    "address": "Andheri East, MIDC Road, Mumbai - 400093"
  },
  {
    "name": "Saheli Mahila Adhar",
    "services": ["Legal Aid", "Counseling"],
    "languages": ["Marathi", "Hindi"],
    "verified": true,
    "contact": "+91-22-27712345",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.000000,
    "lng": 73.010000,
    "address": "Panvel City, Near Railway Station, Navi Mumbai - 410206"
  },
  {
    "name": "VIMOCHANA Women's Cell",
    "services": ["Shelter"],
    "languages": ["English", "Marathi"],
    "verified": false,
    "contact": "+91-22-40123456",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.050000,
    "lng": 72.885000,
    "address": "Sion West, Koliwada Road, Mumbai - 400022"
  },
  {
    "name": "Ekta Mahila Mandal",
    "services": ["Counseling", "Medical Help"],
    "languages": ["Hindi", "Marathi"],
    "verified": true,
    "contact": "+91-22-25987654",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.150000,
    "lng": 72.940000,
    "address": "Bhandup West, LBS Road, Mumbai - 400078"
  },
  {
    "name": "Mumbai Legal Advisory Group",
    "services": ["Legal Aid"],
    "languages": ["English", "Hindi"],
    "verified": true,
    "contact": "+91-22-67678989",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 18.950000,
    "lng": 72.825000,
    "address": "Nariman Point, Free Press House, Mumbai - 400021"
  },
  {
    "name": "Aadarsh Mahila Ashram",
    "services": ["Shelter", "Rehabilitation"],
    "languages": ["Marathi"],
    "verified": true,
    "contact": "+91-20-27654321",
    "region": "Pune",
    "state": "Maharashtra",
    "lat": 18.630000,
    "lng": 73.730000,
    "address": "Tathawade, Near Mumbai-Pune Expressway, Pune - 411033"
  },
  {
    "name": "Pune Crisis Intervention Cell",
    "services": ["Counseling", "Medical Help"],
    "languages": ["Hindi", "English"],
    "verified": true,
    "contact": "+91-20-40506070",
    "region": "Pune",
    "state": "Maharashtra",
    "lat": 18.525000,
    "lng": 73.865000,
    "address": "Koregaon Park, Lane 6, Pune - 411001"
  },
  {
    "name": "Mahila Adhikar Abhiyan, Pune",
    "services": ["Legal Aid"],
    "languages": ["Marathi", "Hindi"],
    "verified": true,
    "contact": "+91-20-26901234",
    "region": "Pune",
    "state": "Maharashtra",
    "lat": 18.570000,
    "lng": 73.900000,
    "address": "Wagholi Road, Near Raisoni College, Pune - 412207"
  },
  {
    "name": "Jyoti Women's Shelter, Thane",
    "services": ["Shelter", "Rehabilitation"],
    "languages": ["Marathi", "Hindi"],
    "verified": true,
    "contact": "+91-22-25332211",
    "region": "Thane",
    "state": "Maharashtra",
    "lat": 19.225000,
    "lng": 73.000000,
    "address": "Wagle Estate, Road No. 22, Thane - 400604"
  },
  {
    "name": "Nashik Legal Helpdesk",
    "services": ["Legal Aid", "Counseling"],
    "languages": ["Marathi", "English"],
    "verified": true,
    "contact": "+91-253-2340011",
    "region": "Nashik",
    "state": "Maharashtra",
    "lat": 20.010000,
    "lng": 73.780000,
    "address": "College Road, Near BSNL Office, Nashik - 422005"
  },
  {
    "name": "Aurangabad Women Trust",
    "services": ["Counseling"],
    "languages": ["Hindi", "Marathi"],
    "verified": false,
    "contact": "+91-240-6677889",
    "region": "Aurangabad",
    "state": "Maharashtra",
    "lat": 19.850000,
    "lng": 75.320000,
    "address": "Osmanpura, Near City Chowk, Aurangabad - 431001"
  },
  {
    "name": "Satara Women's Rights Cell",
    "services": ["Legal Aid", "Shelter"],
    "languages": ["Marathi"],
    "verified": true,
    "contact": "+91-2162-234000",
    "region": "Satara",
    "state": "Maharashtra",
    "lat": 17.680000,
    "lng": 74.000000,
    "address": "Powai Naka, Opposite Bus Depot, Satara - 415001"
  },
  {
    "name": "Navi Mumbai Mahila Shakti",
    "services": ["Rehabilitation", "Counseling"],
    "languages": ["Hindi", "English"],
    "verified": true,
    "contact": "+91-22-27701010",
    "region": "Mumbai",
    "state": "Maharashtra",
    "lat": 19.015000,
    "lng": 73.050000,
    "address": "Koperkhairane Sector 15, Navi Mumbai - 400709"
  },
  {
    "name": "Pune Legal Aid Society",
    "services": ["Legal Aid"],
    "languages": ["Marathi", "English"],
    "verified": true,
    "contact": "+91-20-25654321",
    "region": "Pune",
    "state": "Maharashtra",
    "lat": 18.510000,
    "lng": 73.845000,
    "address": "Laxmi Road, Near City Post, Pune - 411030"
  },
  {
    "name": "Kolhapur Aadhar Kendra",
    "services": ["Shelter", "Medical Help"],
    "languages": ["Marathi", "Hindi"],
    "verified": true,
    "contact": "+91-231-6600770",
    "region": "Kolhapur",
    "state": "Maharashtra",
    "lat": 16.690000,
    "lng": 74.230000,
    "address": "Shahupuri Area, Kolhapur - 416001"
  },
  // ===============================================
  // 3. REST OF INDIA (30 ENTRIES)
  // ===============================================
  // 3.1. New Delhi (10 Entries)
  {
    "name": "Jagori",
    "services": ["Counseling", "Rehabilitation", "Legal Aid"],
    "languages": ["Hindi", "English", "Punjabi"],
    "verified": true,
    "contact": "+91-11-26692879",
    "region": "New Delhi",
    "state": "Delhi",
    "lat": 28.635700,
    "lng": 77.224400,
    "address": "M-28, Saket, Near PVR Complex, New Delhi - 110017"
  },
  {
    "name": "Lawyers Collective Women's Rights Initiative",
    "services": ["Legal Aid", "Policy Advocacy"],
    "languages": ["English", "Hindi"],
    "verified": true,
    "contact": "+91-11-24370044",
    "region": "New Delhi",
    "state": "Delhi",
    "lat": 28.583400,
    "lng": 77.216300,
    "address": "4th Floor, Lawyers Chambers, Lodhi Road, New Delhi - 110003"
  },
  {
    "name": "Delhi Commission for Women (DCW)",
    "services": ["Legal Aid", "Counseling", "Shelter", "Medical Help"],
    "languages": ["Hindi", "English", "Punjabi"],
    "verified": true,
    "contact": "181 (Helpline)",
    "region": "New Delhi",
    "state": "Delhi",
    "lat": 28.613900,
    "lng": 77.209000,
    "address": "C-Block, Vikas Bhawan II, Civil Lines, New Delhi - 110054"
  },
  {
    "name": "Shakti Vahini",
    "services": ["Legal Aid", "Shelter", "Rehabilitation"],
    "languages": ["Hindi", "English"],
    "verified": true,
    "contact": "+91-11-42244224",
    "region": "New Delhi",
    "state": "Delhi",
    "lat": 28.665000,
    "lng": 77.235000,
    "address": "Rani Jhansi Road, Near New Delhi Railway Station, New Delhi - 110006"
  },
  {
    "name": "All India Women's Conference (AIWC)",
    "services": ["Counseling", "Shelter"],
    "languages": ["English", "Hindi"],
    "verified": true,
    "contact": "+91-11-23389680",
    "region": "New Delhi",
    "state": "Delhi",
    "lat": 28.625000,
    "lng": 77.228000,
    "address": "6, Bhagwan Das Road, Near Supreme Court, New Delhi - 110001"
  },
  {
    "name": "Vimochana Delhi",
    "services": ["Rehabilitation", "Counseling"],
    "languages": ["Hindi"],
    "verified": false,
    "contact": "+91-11-47001000",
    "region": "New Delhi",
    "state": "Delhi",
    "lat": 28.605000,
    "lng": 77.170000,
    "address": "Pusa Road, Near Karol Bagh Metro Station, New Delhi - 110005"
  },
  {
    "name": "Kalyani Legal Services",
    "services": ["Legal Aid", "Medical Help"],
    "languages": ["English", "Hindi"],
    "verified": true,
    "contact": "+91-11-26005000",
    "region": "New Delhi",
    "state": "Delhi",
    "lat": 28.555000,
    "lng": 77.275000,
    "address": "Jasola Vihar, Near Apollo Hospital, New Delhi - 110025"
  },
  {
    "name": "Saheli Women's Resource Centre",
    "services": ["Shelter", "Rehabilitation"],
    "languages": ["Hindi", "Punjabi"],
    "verified": true,
    "contact": "+91-11-25556677",
    "region": "New Delhi",
    "state": "Delhi",
    "lat": 28.700000,
    "lng": 77.100000,
    "address": "Rohini Sector 16, Near MCD School, New Delhi - 110085"
  },
  {
    "name": "Disha Crisis Support",
    "services": ["Counseling", "Legal Aid"],
    "languages": ["English", "Hindi"],
    "verified": true,
    "contact": "+91-11-43004300",
    "region": "New Delhi",
    "state": "Delhi",
    "lat": 28.680000,
    "lng": 77.200000,
    "address": "Model Town II, North Delhi, New Delhi - 110009"
  },
  {
    "name": "Nari Chetna Kendra, Delhi",
    "services": ["Medical Help", "Counseling", "Shelter"],
    "languages": ["Hindi"],
    "verified": true,
    "contact": "+91-11-23340011",
    "region": "New Delhi",
    "state": "Delhi",
    "lat": 28.590000,
    "lng": 77.230000,
    "address": "Lajpat Nagar IV, Central Market, New Delhi - 110024"
  },
  // 3.2. Karnataka (10 Entries)
  {
    "name": "Vimochana - Forum for Women's Rights, Bangalore",
    "services": ["Legal Aid", "Counseling", "Shelter"],
    "languages": ["Kannada", "English", "Hindi"],
    "verified": true,
    "contact": "+91-80-25492782",
    "region": "Bangalore",
    "state": "Karnataka",
    "lat": 12.971600,
    "lng": 77.594600,
    "address": "St. Mark's Road, Near MG Road, Bangalore - 560001"
  },
  {
    "name": "Swabhiman Women's Collective",
    "services": ["Rehabilitation", "Counseling"],
    "languages": ["Kannada", "English"],
    "verified": true,
    "contact": "+91-80-41235678",
    "region": "Bangalore",
    "state": "Karnataka",
    "lat": 12.934000,
    "lng": 77.620000,
    "address": "Koramangala 8th Block, Near Forum Mall, Bangalore - 560095"
  },
  {
    "name": "Mahila Samakhya, Karnataka",
    "services": ["Legal Aid", "Shelter"],
    "languages": ["Kannada", "Hindi"],
    "verified": true,
    "contact": "+91-80-26569000",
    "region": "Bangalore",
    "state": "Karnataka",
    "lat": 12.910000,
    "lng": 77.640000,
    "address": "Jayanagar 4th Block, Near South End Circle, Bangalore - 560041"
  },
  {
    "name": "Vanita Sahayavani (Police Helpline)",
    "services": ["Legal Aid", "Counseling", "Medical Help"],
    "languages": ["Kannada", "English", "Tamil"],
    "verified": true,
    "contact": "+91-80-22943225",
    "region": "Bangalore",
    "state": "Karnataka",
    "lat": 12.978000,
    "lng": 77.570000,
    "address": "Infantry Road, Police Commissioner's Office, Bangalore - 560001"
  },
  {
    "name": "Ondede Women's Trust",
    "services": ["Rehabilitation", "Medical Help"],
    "languages": ["Kannada"],
    "verified": false,
    "contact": "+91-80-40102030",
    "region": "Bangalore",
    "state": "Karnataka",
    "lat": 13.030000,
    "lng": 77.560000,
    "address": "Malleshwaram 18th Cross, Near Sampige Road, Bangalore - 560003"
  },
  {
    "name": "Mysore Mahila Adhikar",
    "services": ["Legal Aid", "Counseling"],
    "languages": ["Kannada"],
    "verified": true,
    "contact": "+91-821-2401010",
    "region": "Mysore",
    "state": "Karnataka",
    "lat": 12.305000,
    "lng": 76.650000,
    "address": "Sayyaji Rao Road, Near K.R. Circle, Mysore - 570001"
  },
  {
    "name": "Mangalore Women's Aid",
    "services": ["Shelter", "Rehabilitation"],
    "languages": ["Tulu", "Kannada", "English"],
    "verified": true,
    "contact": "+91-824-2456789",
    "region": "Mangalore",
    "state": "Karnataka",
    "lat": 12.914100,
    "lng": 74.856000,
    "address": "Kadri Road, Near St. Aloysius College, Mangalore - 575003"
  },
  {
    "name": "Hubli-Dharwad Women Trust",
    "services": ["Counseling", "Medical Help"],
    "languages": ["Kannada", "Marathi"],
    "verified": true,
    "contact": "+91-836-2345566",
    "region": "Hubli",
    "state": "Karnataka",
    "lat": 15.364700,
    "lng": 75.124000,
    "address": "Bhavani Nagar, Gokul Road, Hubli - 580030"
  },
  {
    "name": "Karunashraya Women's Unit",
    "services": ["Shelter", "Rehabilitation"],
    "languages": ["Kannada", "Hindi"],
    "verified": true,
    "contact": "+91-80-60005000",
    "region": "Bangalore",
    "state": "Karnataka",
    "lat": 12.900000,
    "lng": 77.700000,
    "address": "Sarjapur Road, Near Wipro, Bangalore - 560102"
  },
  {
    "name": "Jan Sahas Social Initiative",
    "services": ["Legal Aid", "Counseling"],
    "languages": ["English", "Hindi"],
    "verified": true,
    "contact": "+91-80-25228000",
    "region": "Bangalore",
    "state": "Karnataka",
    "lat": 13.000000,
    "lng": 77.650000,
    "address": "Indiranagar 100 Ft Road, Near Metro Station, Bangalore - 560038"
  },
  // 3.3. Tamil Nadu & West Bengal (10 Entries)
  {
    "name": "International Foundation for Crime Prevention (IFCP)",
    "services": ["Legal Aid", "Counseling"],
    "languages": ["Tamil", "English"],
    "verified": true,
    "contact": "+91-44-24956789",
    "region": "Chennai",
    "state": "Tamil Nadu",
    "lat": 13.082700,
    "lng": 80.270700,
    "address": "Mylapore, Near Luz Corner, Chennai - 600004"
  },
  {
    "name": "Swayam, Kolkata",
    "services": ["Counseling", "Legal Aid", "Shelter"],
    "languages": ["Bengali", "English", "Hindi"],
    "verified": true,
    "contact": "+91-33-24754408",
    "region": "Kolkata",
    "state": "West Bengal",
    "lat": 22.572600,
    "lng": 88.363900,
    "address": "Jodhpur Park, Near South City Mall, Kolkata - 700068"
  },
  {
    "name": "Legal Aid Centre for Women, Chennai",
    "services": ["Legal Aid", "Rehabilitation"],
    "languages": ["Tamil", "English"],
    "verified": true,
    "contact": "+91-44-42001000",
    "region": "Chennai",
    "state": "Tamil Nadu",
    "lat": 13.030000,
    "lng": 80.240000,
    "address": "Nungambakkam High Road, Near US Consulate, Chennai - 600006"
  },
  {
    "name": "New Light, Kolkata",
    "services": ["Shelter", "Medical Help", "Rehabilitation"],
    "languages": ["Bengali", "Hindi"],
    "verified": true,
    "contact": "+91-33-24567890",
    "region": "Kolkata",
    "state": "West Bengal",
    "lat": 22.540000,
    "lng": 88.340000,
    "address": "Kidderpore Docks Area, Near Port Trust, Kolkata - 700023"
  },
  {
    "name": "Madurai Women's Action Group",
    "services": ["Counseling", "Shelter"],
    "languages": ["Tamil"],
    "verified": true,
    "contact": "+91-452-2531010",
    "region": "Madurai",
    "state": "Tamil Nadu",
    "lat": 9.925200,
    "lng": 78.119800,
    "address": "Anna Nagar Main Road, Near Collector Office, Madurai - 625020"
  },
  {
    "name": "Women's Initiatives, Hyderabad",
    "services": ["Legal Aid", "Counseling"],
    "languages": ["Telugu", "English", "Hindi"],
    "verified": true,
    "contact": "+91-40-23301010",
    "region": "Hyderabad",
    "state": "Telangana",
    "lat": 17.385000,
    "lng": 78.486700,
    "address": "Banjara Hills Road No. 12, Near KBR Park, Hyderabad - 500034"
  },
  {
    "name": "Hyderabad Mahila Abhyudaya",
    "services": ["Shelter", "Rehabilitation"],
    "languages": ["Telugu", "Hindi"],
    "verified": true,
    "contact": "+91-40-27778899",
    "region": "Hyderabad",
    "state": "Telangana",
    "lat": 17.410000,
    "lng": 78.470000,
    "address": "Begumpet, Near Airport Road, Hyderabad - 500016"
  },
  {
    "name": "Ahmedabad Women's Support Trust",
    "services": ["Legal Aid", "Medical Help"],
    "languages": ["Gujarati", "Hindi"],
    "verified": true,
    "contact": "+91-79-26850011",
    "region": "Ahmedabad",
    "state": "Gujarat",
    "lat": 23.022500,
    "lng": 72.571400,
    "address": "Ellisbridge, Ashram Road, Near Town Hall, Ahmedabad - 380006"
  },
  {
    "name": "Jaipur Nari Adhikar Samiti",
    "services": ["Counseling", "Shelter"],
    "languages": ["Hindi", "Rajasthani"],
    "verified": true,
    "contact": "+91-141-2701010",
    "region": "Jaipur",
    "state": "Rajasthan",
    "lat": 26.912400,
    "lng": 75.787300,
    "address": "Bapu Nagar, Near University of Rajasthan, Jaipur - 302015"
  },
  {
    "name": "Patna Mahila Suraksha Manch",
    "services": ["Legal Aid", "Rehabilitation"],
    "languages": ["Hindi", "Bhojpuri"],
    "verified": false,
    "contact": "+91-612-2571234",
    "region": "Patna",
    "state": "Bihar",
    "lat": 25.594100,
    "lng": 85.137600,
    "address": "Fraser Road, Near Patna Junction, Patna - 800001"
  }
];

async function importNgos() {
  const batch = db.batch();
  const ngosRef = db.collection('ngos');
  
  ngos.forEach(ngo => {
    const docRef = ngosRef.doc(); // Auto-generate ID
    batch.set(docRef, ngo);
  });

  await batch.commit();
  console.log(`Successfully imported ${ngos.length} NGOs`);
}

importNgos().catch(console.error);